### PR TITLE
Preview of documentation

### PR DESCRIPTION
**Pull request by devmotion**

### CODE REVIEW

**Comment by devmotion** [comment]
Ah this needs more changes, the custom `DeployConfig` overwrites the `pull_request` event and so Documenter does not create a preview build but instead rebuilds the actual docs since it assumes we pushed to master.

It seems one should also not build both `stable` and `dev` in a PR. In general, maybe there should be separate triggers for the `stable` builds only if there is a new release of Turing - it seems a bit strange to rebuild it every time the action is executed.

**Comment by devmotion** [comment]
Maybe one should first separate the repo more clearly from Turing, as discussed in https://github.com/TuringLang/Turing.jl/issues/1474.

**Comment by cpfiffer** [comment]
> Maybe one should first separate the repo more clearly from Turing, as discussed in [TuringLang/Turing.jl#1474](https://github.com/TuringLang/Turing.jl/issues/1474).

I'm also not sure what you mean here -- everything that's in this repo is basically just website skeleton. The whole point of `make.jl` is to go grab any of Turing docs and build them in the website format. It's very separate from Turing.

**Comment by devmotion** [comment]
> I'm also not sure what you mean here -- everything that's in this repo is basically just website skeleton. The whole point of make.jl is to go grab any of Turing docs and build them in the website format. It's very separate from Turing.

I got confused by the setup and only realized this later. Just ignore this comment :slightly_smiling_face:

**Review by yebai — APPROVED** [review]

**Comment by devmotion** [comment]
This is not useful, as mentioned above it just rebuilds the stable and dev version of the docs. However, the main motivation would be to build it in a separate folder for each PR.

**Pull request closed without merging**
